---

version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: development
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3308:3306"
  web:
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      DATABASE_DEV_HOST: db
      DATABASE_DEV_USERNAME: root
      DATABASE_DEV_PASSWORD: password
      DATABASE_STG_HOST: db
      DATABASE_STG_USERNAME: root
      DATABASE_STG_PASSWORD: password
    build:
      context: .
      dockerfile: Dockerfile
    command: bin/rails s -b 0.0.0.0 -p 3000
    volumes:
      - .:/opt/
    ports:
      - "3005:3000"
    links:
      - db
    depends_on:
      - db

