# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 2 } %>
  timeout: 5000

development:
  <<: *default
  host: <%= ENV.fetch("DATABASE_DEV_HOST") { '127.0.0.1' } %>
  database: <%= ENV.fetch("DATABASE_DEV") { 'development' } %>
  username: <%= ENV["DATABASE_DEV_USERNAME"] %>
  password: <%= ENV["DATABASE_DEV_PASSWORD"] %>

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
